base_url = "https://cv.securesql.info"
compile_sass = true
title = "Menerick's CyberForge: Securing Your Tomorrow, Today"
description = "Security Operator"
generate_feeds = true
feed_filenames = ["atom.xml"]
build_search_index = true
taxonomies = [
  { name = "tags", generate_feeds = true },
]

[markdown]
[markdown.highlighting]
code = true
theme = "catppuccin-mocha"

[extra]
first_name = "John"
last_name = "Menerick"
address = "Castro Valley, California"
email = "john.menerick+se@owasp.org"
favicon = "/favicon.ico"
avatar = "/media/avatar.webp"

katex = false
show_about = true
show_skills = true
show_projects = true
show_challengeaccepted = true
show_experience = true
show_education = true
show_credentials = true
show_blog = false
show_research = true
