base_url = "https://cv.securesql.info"
compile_sass = true
title = "Menerick's CyberForge: Securing Your Tomorrow, Today"
description = "Security Operator"
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
first_name = "John"
last_name = "Menerick"
address = "Castro Valley, California"
email = "john.menerick+se@owasp.org"
favicon = "/favicon.ico"
avatar = "/media/avatar.png"

katex = false
show_about = true
show_skills = true
show_projects = true
show_challengeaccepted = true
show_experience = true
show_education = true
show_credentials = true
show_blog = true
show_research = true
